### ISSUE TITLE
The link in the readme to the forum is wrong

### ISSUE THREAD

**Issue by DuncanLithgow** [yorikvanhavre/CADExchanger#6]
The link in the readme to the forum is wrong. I assume the intended target is https://forum.freecadweb.org/viewtopic.php?f=9&t=22227&p=462421

"Further discussions about this Addon will get better exposure when posting to its _dedicated FreeCAD forum thread_. Please include version of FreeCAD and make sure you are running the most up to date version of the Addon."

**Comment by yorikvanhavre** [comment]
Keen eye :) Thanks!!
